#!/bin/bash
#COLOUR
echo ""
cyan='\e[0;36m'
green='\e[0;32m'
greenl='\e[1;32m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
yellowl='\e[1;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
orange='\e[38;5;166m'
#color-end
echo -e "$greenl" "     [ ✔ ] Downloading config files──────────────────█<><><>───[ Wait ]<><><>  █──"
rm -rf *.zip 2>&1
rm -rf torrc 2>&1
rm -rf proxychains.conf 2>&1
wget https://github.com/efxtv/Single-Click-Proxychains/raw/main/file.zip -q --show-progress
if [[ -e file.zip ]]; then
#if-e  >/dev/null; then
unzip file.zip > /dev/null 2>&1
chmod +x * 2>&1
rm -rf *.zip 2>&1
mv torrc proxychains.conf 2 2>&1
echo -e "$greenl" "     [ ✔ ] Installing config files───────────────────█<><><>───[ Wait ]<><><>  █──"
sleep 3
cd 2
sudo rm -rf /etc/proxychains.conf 2>&1
#echo "proxychains exixt or not after remove"
ls /etc/|grep proxychains.conf 2>&1
sleep 1
sudo cp proxychains.conf /etc 2>&1
#echo "PRXc exixt or not after copy" 2>&1
#ls /etc/|grep proxychains.conf 2>&1
sleep 1
sudo rm -rf /etc/tor/torrc 2>&1
#echo "Tor exixt or not after remove"
ls /etc/tor|grep torrc 2>&1
sleep 1
sudo cp torrc /etc/tor/ 2>&1
#echo "Tor exixt or not after copy"
#ls /etc/tor|grep torrc 
echo -e "$greenl" "     [ ✔ ] Installation ───<><>OKAY<><>──────────────█<><><>───[ OKAY ]<><><>  █──"
sleep 2
echo -e "$greenl" "     [ ✔ ] Starting tor service──────────────────────█<><><>───[ Wait ]<><><>  █──"
sleep 3
sudo service tor stop 2>&1
sudo service tor start 2>&1
sleep 2
echo -e "$greenl" "     [ ✔ ] Tor status────────────────────────────────█<><><>───[ Active ]<><><>  █──"
sleep 3
echo -e "$greenl" "     [ ✔ ] Please choose start────────────────────────────────█<><><>───[ Strt ]<><><>  █──"
sleep 3
echo -e "$greenl" "     [ ✔ ] Back to main menu────────────────────────────────█<><><>───[ Active ]<><><>  █──"
sleep 3
cd ..
clear
bash Run.sh
exit
else
echo -e "$greenl" "     [ ! ] Download error ────────────────────────────█<><><>───[ Wget required ]<><><>  █──"
sleep 2
echo -e "$greenl" "     [ ! ] Installing ────────────────────────────────█<><><>───[ Wget ]<><><>  █──"
sleep 3
xterm -T "<><><>█── INSTALL ME NOW█──<><><>" -geometry 100x40 -e "sudo apt-get install wget -y"
echo -e "$greenl" "     [ ✔ ] Installed ────────────────────────────────█<><><>───[ Wget ]<><><>  █──"
echo -e "$greenl" "     [ ✔ ] Installed ────────────────────────────────█<><><>───[ Wget ]<><><>  █──"
echo -e "$greenl" "     [ ✔ ] Downloading config files──────────────────█<><><>───[ Wait ]<><><>  █──"
wget https://github.com/efxtv/Single-Click-Proxychains/raw/main/file.zip -q --show-progress
unzip file.zip > /dev/null 2>&1
chmod +x *
rm -rf file.zip
exit
fi
