#!/bin/bash
#COLOUR
echo ""
cyan='\e[0;36m'
green='\e[0;32m'
greenl='\e[1;32m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
yellowl='\e[1;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
orange='\e[38;5;166m'
#color-end
chmod -R 755 *
echo -e "$green" ""
echo -e " +<><><><><><><><><><><><><><><>>+ ░░░░░░███████]$greenl ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$green"
echo -e "<> $greenl  Proxychains + Tor$green        <>      ▂▄▅█████████▅▄▃▂"
echo -e "<>$greenl      By EFX Tv$green             <>     [███████████████████]."
echo -e "$green" "+<><><><><><><><><><><><><><><>>+     ◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..."
echo ""
echo -e "$greenl" "──────< o > <><><>─────────────ALL OKAY─────────────<><><>───[ OKAY ]──<><><>──────"
echo ""
echo -e "$greenl""    █▀▀ █─█ █▀▀█ █── █▀▀█ █▀▀█ █▀▀ 　 ▀▀█▀▀ █──█ █▀▀ 　 █───█ █▀▀█ █▀▀█ █── █▀▀▄ "
echo "    █▀▀ ▄▀▄ █──█ █── █──█ █▄▄▀ █▀▀ 　 ──█── █▀▀█ █▀▀ 　 █▄█▄█ █──█ █▄▄▀ █── █──█ "
echo "    ▀▀▀ ▀─▀ █▀▀▀ ▀▀▀ ▀▀▀▀ ▀─▀▀ ▀▀▀ 　 ──▀── ▀──▀ ▀▀▀ 　 ─▀─▀─ ▀▀▀▀ ▀─▀▀ ▀▀▀ ▀▀▀─"
echo ""
echo -e "$green""████████████████████████████████████████████████████████████████████████████████████████"
echo "█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░███░░░░░░░░░░░░░░█░░░░░░░░██░░░░░░░░█░░░░░░░░██░░░░░░░░█"
echo "█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█"
echo "█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░░░▄▀░░██░░▄▀░░░░█░░░░▄▀░░██░░▄▀░░░░█"
echo "█░░▄▀░░██░░▄▀░░█░░▄▀░░████░░▄▀░░███░░▄▀░░██░░▄▀░░███░░▄▀▄▀░░▄▀▄▀░░█████░░▄▀▄▀░░▄▀▄▀░░███"
echo "█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░██░░▄▀░░███░░░░▄▀▄▀▄▀░░░░█████░░░░▄▀▄▀▄▀░░░░███"
echo "█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀░░██░░▄▀░░█████░░▄▀▄▀▄▀░░█████████░░░░▄▀░░░░█████"
echo "█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░░░███░░▄▀░░██░░▄▀░░███░░░░▄▀▄▀▄▀░░░░█████████░░▄▀░░███████"
echo "█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█████░░▄▀░░██░░▄▀░░███░░▄▀▄▀░░▄▀▄▀░░█████████░░▄▀░░███████"
echo "█░░▄▀░░█████████░░▄▀░░██░░▄▀░░░░░░█░░▄▀░░░░░░▄▀░░█░░░░▄▀░░██░░▄▀░░░░███████░░▄▀░░███████"
echo "█░░▄▀░░█████████░░▄▀░░██░░▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░███████░░▄▀░░███████"
echo "█░░░░░░█████████░░░░░░██░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░██░░░░░░░░███████░░░░░░Chains█"
echo "████████████████████  █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █   █   █    █"
echo "██ █ █ █ █ █ █ █ █ █                     ███████████████████████████████████████████████ "
echo -e "█$greenl──<>──192.168.0.1:8854<>───────────$greenl[CONNECTED]──────$green █ $greenl SUBSCRIBE  $green██$greenl EFXTV          $green██"
echo "████████████████████████████████████████████████████████████████████████████████████████"
echo -e "$greenl" ""
echo "        ▄▀█ █░█ ▀█▀ █▀█ █▀▄▀█ ▄▀█ ▀█▀ █ █▀▀   █ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░ █▀▀ █▀█"
echo "        █▀█ █▄█ ░█░ █▄█ █░▀░█ █▀█ ░█░ █ █▄▄   █ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄ ██▄ █▀▄"
echo ""
#SRC started
echo -e "$greenl" "     [ ✔ ] Checking tor────────────────────█──<><><>───[ CHECK ]<><><>  █──"
#which tor > /dev/null 2>&1
sleep 1
if which tor >/dev/null; then
echo -e "$greenl" "     [ ✔ ] Tor──────────────────────────█─────<><><>───[ FOUND ]<><><>  █──"
else
echo -e " $greenl     [$red X $green] Tor───────────────────────────█────<><><>───[ $red███$green NOT FOUND $red ███$green ]<><><>  █──"
sleep 1
echo -e "$greenl" "     [ I ] Installing Tor────────────────────█<><><>───[ INSTALL ]<><><>  █──"
sleep 3
xterm -T "<><><>█── INSTALL ME NOW█──<><><>" -geometry 100x40 -e "sudo apt-get install tor -y"
echo -e "$greenl" "     [ ✔ ] Tor installed──────────────█───────<><><>───[ GREAT ]<><><>  █──"
fi
echo -e "$greenl" "     [ ✔ ] Proxy chains──────────────█────────<><><>───[ CHECK ]<><><>  █──"
#which proxychain > /dev/null 2>&1
sleep 1
if which proxychains >/dev/null; then
echo -e "$greenl" "     [ ✔ ] Proxy chains───────────────█───────<><><>───[ FOUND ]<><><>  █──"
else
echo -e " $greenl [$red X $green] Proxy chains─────────────────────█─<><><>───[ $red███$green NOT FOUND $red ███$green ]<><><>  █──"
sleep 1
echo -e "$greenl" "     [ I ] Installing Proxy chains──────█─────<><><>───[ INSTALL ]<><><>  █──"
sleep 3
xterm -T "<><><>█── INSTALL ME NOW█──<><><>" -geometry 100x40 -e "sudo apt-get install proxychains -y"
echo -e "$greenl" "     [ ✔ ] Proxy chains installed─────────█───<><><>───[ GREAT ]<><><>  █──"
fi
#which proxychain > /dev/null 2>&1
sleep 1
if which zip >/dev/null; then
echo -e "$greenl" "     [ ✔ ] Zip───────────────────────────────█<><><>───[ FOUND ]<><><>  █──"
else
echo -e " $greenl [$red X $green] Zip────────────────────────────█───<><><>───[ $red███$green NOT FOUND $red ███$green ]<><><>  █──"
sleep 1
echo -e "$greenl" "     [ I ] Installing Zip─────────────█───────<><><>───[ INSTALL ]<><><>  █──"
sleep 3
xterm -T "<><><>█── INSTALL ME NOW█──<><><>" -geometry 100x40 -e "sudo apt-get install zip -y"
echo -e "$greenl" "     [ ✔ ] Zip installed──────────────█───────<><><>───[ GREAT ]<><><>  █──"
fi
#which proxychain > /dev/null 2>&1
sleep 1
if which unzip >/dev/null; then
echo -e "$greenl" "     [ ✔ ] Unzip──────────────────────────█───<><><>───[ FOUND ]<><><>  █──"
else
echo -e " $green [$red X $green] Unzip────────────────────────────█─<><><>───[ $red███$green NOT FOUND $red ███$green ]<><><>  █──"
sleep 1
echo -e "$greenl" "     [ I ] Installing Unzip──────────────█───────<><><>[ INSTALL ]<><><>  █──"
sleep 3
xterm -T "<><><>█── INSTALL ME NOW█──<><><>" -geometry 100x40 -e "sudo apt-get install unzip -y"
echo -e "$greenl" "     [ ✔ ] Unzip installed───────────────█────<><><>──[  GREAT ]<><><>  █──"
sleep 3
fi
#Checks------------------------------------------------------------------------checks
if which tor >/dev/null; then
echo -e "$greenl" "     [ ✔ ] Refreshing checks────────────────█─<><><>───[ CHECK ]<><><>  █──"
echo
echo -e "$greenl" "    ██████████████████████████████████████████████████████████████████████"
echo -e "$greenl" "    █                                                                    █  "
echo -e "$greenl" "    █ [ ✔ ] Tor────────────────────█───────────<><><>───[ FOUND ]<><><>  █──"
sleep 2
else
sleep 2
echo -e "     $greenl [$red X $green] Something went wrong contact Admin─█<><><>───[ $red███$green ERROR $red ███$green ]<><><>  █──"
exit
fi
if which proxychains >/dev/null; then
echo -e "$greenl" "    █ [ ✔ ] Proxy chains────────────────█──────<><><>───[ FOUND ]<><><>  █──"
sleep 2
else
sleep 2
echo -e "$red" "     [ X ] Something went wrong contact Admin─────█<><><>───[ $red███$green ERROR $red ███$green ]<><><>  █──"
exit
fi
if which tor >/dev/null; then
echo -e "$greenl" "    █ [ ✔ ] Zip────────────────────█───────────<><><>───[ FOUND ]<><><>  █──"
sleep 2
else
sleep 2
echo -e "$red" "     [ X ] Something went wrong contact Admin────────────────────█─<><><>───[ $red███$green ERROR $red ███$green ]<><><>  █──"
exit
fi
if which unzip >/dev/null; then
echo -e "$greenl" "    █ [ ✔ ] Unzip────────────────█─────────────<><><>───[ FOUND ]<><><>  █──"
echo -e "$greenl" "    █                                                                    █  "
echo -e "$greenl" "    ██████████████████████████████████████████████████████████████████████"
sleep 2
echo
echo -e "$greenl" "──────< o > <><><>─────────────ALL OKAY─────────────<><><>───[ OKAY ]──<><><>──────"
bash con
else
sleep 2
echo -e "$red" " [ X ]    █Something went wrong contact Admin────────────────────█─<><><>──[ $red███$green ERROR $red ███$green ]<><><>  █──"
exit
fi
